baseURL = "https://yyq83.github.io/notion-hugo-blog"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "DoIt"

[params.home.profile]
  # Gravatar 邮箱, 用于优先在主页显示的头像
  gravatarEmail = "yangyinqi85@gmal.com"
  # 主页显示头像的 URL
  avatarURL = "/images/avatar.webp"
  # 头像的链接指向的 URL
  avatarLinkURL = "yangyinqi85@gmail.com"
