baseURL = "https://yyq83.github.io/notion-hugo-blog"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "DoIt"

[author]
name = "PCloud"
email = "heige.pcloud@outlook.com"
link = "https://github.com/HEIGE-PCloud"

[outputs]
  home = ["HTML", "RSS", "JSON"]
